[package]
name = "engine"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Native Rust engine for HD2 Repatcher unit and audio mods"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
rayon = { workspace = true }
lz4_flex = { workspace = true }
dirs = { workspace = true }
indexmap = { workspace = true }
toml = { workspace = true }
